export const corPrimaria = 'hsl(220, 15%, 55%)'
export const fundoClaro = 'hsl(212, 45%, 89%)'
export const conteudoClaro = 'white'
export const textoFundoClaro = 'grey'
export const fundoEscuro = '#363537'
export const conteudoEscuro = '#5c5b5e'
export const textoFundoEscuro = '#fafafafa'
export const textoRodape = '#3785FF'
